# Generated by Django 5.2 on 2026-08-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.CharField(choices=[('disabled', 'Disabled'), ('hourly', 'Every Hour'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('backup_type', models.CharField(choices=[('sql', 'SQL Only'), ('json', 'JSON Only'), ('full', 'Full (SQL + JSON)')], default='full', max_length=20)),
                ('scheduled_time', models.TimeField(default='02:00', help_text='Time of day for daily/weekly backups.')),
                ('scheduled_day', models.PositiveIntegerField(default=0, help_text='Day of week for weekly (0=Mon, 6=Sun).')),
                ('retention_days', models.PositiveIntegerField(default=30, help_text='Keep backups for this many days.')),
                ('auto_cleanup', models.BooleanField(default=True, help_text='Automatically delete old backups.')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_status', models.CharField(blank=True, max_length=20)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backup_schedule',
            },
        ),
    ]
